# coding: utf-8

"""
    Global Forester API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class ObservationFilesApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def get_image(self, observation_id, id, **kwargs):  # noqa: E501
        """get_image  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_image(observation_id, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str observation_id: (required)
        :param str id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_image_with_http_info(observation_id, id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_image_with_http_info(observation_id, id, **kwargs)  # noqa: E501
            return data

    def get_image_with_http_info(self, observation_id, id, **kwargs):  # noqa: E501
        """get_image  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_image_with_http_info(observation_id, id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str observation_id: (required)
        :param str id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['observation_id', 'id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_image" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'observation_id' is set
        if ('observation_id' not in params or
                params['observation_id'] is None):
            raise ValueError("Missing the required parameter `observation_id` when calling `get_image`")  # noqa: E501
        # verify the required parameter 'id' is set
        if ('id' not in params or
                params['id'] is None):
            raise ValueError("Missing the required parameter `id` when calling `get_image`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'observation_id' in params:
            path_params['observationId'] = params['observation_id']  # noqa: E501
        if 'id' in params:
            path_params['id'] = params['id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['image/jpeg'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Authorization Code', 'Client Credentials']  # noqa: E501

        return self.api_client.call_api(
            '/v1/observations/{observationId}/images/{id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_observation_files(self, observation_id, **kwargs):  # noqa: E501
        """get_observation_files  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_observation_files(observation_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str observation_id: (required)
        :return: list[GlobalForesterApiV1ControllersObservationFilesSharedResponseObservationFile]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_observation_files_with_http_info(observation_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_observation_files_with_http_info(observation_id, **kwargs)  # noqa: E501
            return data

    def get_observation_files_with_http_info(self, observation_id, **kwargs):  # noqa: E501
        """get_observation_files  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_observation_files_with_http_info(observation_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str observation_id: (required)
        :return: list[GlobalForesterApiV1ControllersObservationFilesSharedResponseObservationFile]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['observation_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_observation_files" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'observation_id' is set
        if ('observation_id' not in params or
                params['observation_id'] is None):
            raise ValueError("Missing the required parameter `observation_id` when calling `get_observation_files`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'observation_id' in params:
            path_params['observationId'] = params['observation_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Authorization Code', 'Client Credentials']  # noqa: E501

        return self.api_client.call_api(
            '/v1/observations/{observationId}/files', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[GlobalForesterApiV1ControllersObservationFilesSharedResponseObservationFile]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
