# coding: utf-8

"""
    Global Forester API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class TracklogsApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def delete_tracklog(self, project_id, tracklog_id, **kwargs):  # noqa: E501
        """delete_tracklog  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_tracklog(project_id, tracklog_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: (required)
        :param str tracklog_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_tracklog_with_http_info(project_id, tracklog_id, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_tracklog_with_http_info(project_id, tracklog_id, **kwargs)  # noqa: E501
            return data

    def delete_tracklog_with_http_info(self, project_id, tracklog_id, **kwargs):  # noqa: E501
        """delete_tracklog  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_tracklog_with_http_info(project_id, tracklog_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: (required)
        :param str tracklog_id: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['project_id', 'tracklog_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_tracklog" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'project_id' is set
        if ('project_id' not in params or
                params['project_id'] is None):
            raise ValueError("Missing the required parameter `project_id` when calling `delete_tracklog`")  # noqa: E501
        # verify the required parameter 'tracklog_id' is set
        if ('tracklog_id' not in params or
                params['tracklog_id'] is None):
            raise ValueError("Missing the required parameter `tracklog_id` when calling `delete_tracklog`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project_id' in params:
            path_params['projectId'] = params['project_id']  # noqa: E501
        if 'tracklog_id' in params:
            path_params['tracklogId'] = params['tracklog_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain', 'application/json', 'text/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Authorization Code', 'Client Credentials']  # noqa: E501

        return self.api_client.call_api(
            '/v1/projects/{projectId}/tracklogs/{tracklogId}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_tracklog(self, project_id, tracklog_id, **kwargs):  # noqa: E501
        """get_tracklog  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_tracklog(project_id, tracklog_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: (required)
        :param str tracklog_id: (required)
        :return: GlobalForesterApiV1ControllersTracklogsSharedResponseTracklog
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_tracklog_with_http_info(project_id, tracklog_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_tracklog_with_http_info(project_id, tracklog_id, **kwargs)  # noqa: E501
            return data

    def get_tracklog_with_http_info(self, project_id, tracklog_id, **kwargs):  # noqa: E501
        """get_tracklog  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_tracklog_with_http_info(project_id, tracklog_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: (required)
        :param str tracklog_id: (required)
        :return: GlobalForesterApiV1ControllersTracklogsSharedResponseTracklog
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['project_id', 'tracklog_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_tracklog" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'project_id' is set
        if ('project_id' not in params or
                params['project_id'] is None):
            raise ValueError("Missing the required parameter `project_id` when calling `get_tracklog`")  # noqa: E501
        # verify the required parameter 'tracklog_id' is set
        if ('tracklog_id' not in params or
                params['tracklog_id'] is None):
            raise ValueError("Missing the required parameter `tracklog_id` when calling `get_tracklog`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project_id' in params:
            path_params['projectId'] = params['project_id']  # noqa: E501
        if 'tracklog_id' in params:
            path_params['tracklogId'] = params['tracklog_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Authorization Code', 'Client Credentials']  # noqa: E501

        return self.api_client.call_api(
            '/v1/projects/{projectId}/tracklogs/{tracklogId}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GlobalForesterApiV1ControllersTracklogsSharedResponseTracklog',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_tracklogs(self, project_id, **kwargs):  # noqa: E501
        """get_tracklogs  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_tracklogs(project_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: (required)
        :return: list[GlobalForesterApiV1ControllersTracklogsSharedResponseTracklog]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_tracklogs_with_http_info(project_id, **kwargs)  # noqa: E501
        else:
            (data) = self.get_tracklogs_with_http_info(project_id, **kwargs)  # noqa: E501
            return data

    def get_tracklogs_with_http_info(self, project_id, **kwargs):  # noqa: E501
        """get_tracklogs  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_tracklogs_with_http_info(project_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: (required)
        :return: list[GlobalForesterApiV1ControllersTracklogsSharedResponseTracklog]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['project_id']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_tracklogs" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'project_id' is set
        if ('project_id' not in params or
                params['project_id'] is None):
            raise ValueError("Missing the required parameter `project_id` when calling `get_tracklogs`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project_id' in params:
            path_params['projectId'] = params['project_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Authorization Code', 'Client Credentials']  # noqa: E501

        return self.api_client.call_api(
            '/v1/projects/{projectId}/tracklogs', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[GlobalForesterApiV1ControllersTracklogsSharedResponseTracklog]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def post_tracklog(self, project_id, **kwargs):  # noqa: E501
        """post_tracklog  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.post_tracklog(project_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: (required)
        :param GlobalForesterApiV1ControllersTracklogsPostTracklogRequestTracklog body:
        :return: GlobalForesterApiV1ControllersTracklogsSharedResponseTracklog
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.post_tracklog_with_http_info(project_id, **kwargs)  # noqa: E501
        else:
            (data) = self.post_tracklog_with_http_info(project_id, **kwargs)  # noqa: E501
            return data

    def post_tracklog_with_http_info(self, project_id, **kwargs):  # noqa: E501
        """post_tracklog  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.post_tracklog_with_http_info(project_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: (required)
        :param GlobalForesterApiV1ControllersTracklogsPostTracklogRequestTracklog body:
        :return: GlobalForesterApiV1ControllersTracklogsSharedResponseTracklog
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['project_id', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method post_tracklog" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'project_id' is set
        if ('project_id' not in params or
                params['project_id'] is None):
            raise ValueError("Missing the required parameter `project_id` when calling `post_tracklog`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project_id' in params:
            path_params['projectId'] = params['project_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Authorization Code', 'Client Credentials']  # noqa: E501

        return self.api_client.call_api(
            '/v1/projects/{projectId}/tracklogs', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GlobalForesterApiV1ControllersTracklogsSharedResponseTracklog',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def put_tracklog(self, project_id, tracklog_id, **kwargs):  # noqa: E501
        """put_tracklog  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.put_tracklog(project_id, tracklog_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: (required)
        :param str tracklog_id: (required)
        :param GlobalForesterApiV1ControllersTracklogsPutTracklogRequestTracklog body:
        :return: GlobalForesterApiV1ControllersTracklogsSharedResponseTracklog
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.put_tracklog_with_http_info(project_id, tracklog_id, **kwargs)  # noqa: E501
        else:
            (data) = self.put_tracklog_with_http_info(project_id, tracklog_id, **kwargs)  # noqa: E501
            return data

    def put_tracklog_with_http_info(self, project_id, tracklog_id, **kwargs):  # noqa: E501
        """put_tracklog  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.put_tracklog_with_http_info(project_id, tracklog_id, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str project_id: (required)
        :param str tracklog_id: (required)
        :param GlobalForesterApiV1ControllersTracklogsPutTracklogRequestTracklog body:
        :return: GlobalForesterApiV1ControllersTracklogsSharedResponseTracklog
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['project_id', 'tracklog_id', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method put_tracklog" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'project_id' is set
        if ('project_id' not in params or
                params['project_id'] is None):
            raise ValueError("Missing the required parameter `project_id` when calling `put_tracklog`")  # noqa: E501
        # verify the required parameter 'tracklog_id' is set
        if ('tracklog_id' not in params or
                params['tracklog_id'] is None):
            raise ValueError("Missing the required parameter `tracklog_id` when calling `put_tracklog`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project_id' in params:
            path_params['projectId'] = params['project_id']  # noqa: E501
        if 'tracklog_id' in params:
            path_params['tracklogId'] = params['tracklog_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['Authorization Code', 'Client Credentials']  # noqa: E501

        return self.api_client.call_api(
            '/v1/projects/{projectId}/tracklogs/{tracklogId}', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='GlobalForesterApiV1ControllersTracklogsSharedResponseTracklog',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
