# coding: utf-8

"""
    Global Forester API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GlobalForesterApiV1ControllersProjectsSharedResponseProject(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'team_id': 'str',
        'created': 'datetime',
        'updated': 'datetime',
        'name': 'str',
        'links': 'dict(str, str)'
    }

    attribute_map = {
        'id': 'id',
        'team_id': 'teamId',
        'created': 'created',
        'updated': 'updated',
        'name': 'name',
        'links': 'links'
    }

    def __init__(self, id=None, team_id=None, created=None, updated=None, name=None, links=None):  # noqa: E501
        """GlobalForesterApiV1ControllersProjectsSharedResponseProject - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._team_id = None
        self._created = None
        self._updated = None
        self._name = None
        self._links = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if team_id is not None:
            self.team_id = team_id
        if created is not None:
            self.created = created
        if updated is not None:
            self.updated = updated
        if name is not None:
            self.name = name
        if links is not None:
            self.links = links

    @property
    def id(self):
        """Gets the id of this GlobalForesterApiV1ControllersProjectsSharedResponseProject.  # noqa: E501


        :return: The id of this GlobalForesterApiV1ControllersProjectsSharedResponseProject.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this GlobalForesterApiV1ControllersProjectsSharedResponseProject.


        :param id: The id of this GlobalForesterApiV1ControllersProjectsSharedResponseProject.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def team_id(self):
        """Gets the team_id of this GlobalForesterApiV1ControllersProjectsSharedResponseProject.  # noqa: E501


        :return: The team_id of this GlobalForesterApiV1ControllersProjectsSharedResponseProject.  # noqa: E501
        :rtype: str
        """
        return self._team_id

    @team_id.setter
    def team_id(self, team_id):
        """Sets the team_id of this GlobalForesterApiV1ControllersProjectsSharedResponseProject.


        :param team_id: The team_id of this GlobalForesterApiV1ControllersProjectsSharedResponseProject.  # noqa: E501
        :type: str
        """

        self._team_id = team_id

    @property
    def created(self):
        """Gets the created of this GlobalForesterApiV1ControllersProjectsSharedResponseProject.  # noqa: E501


        :return: The created of this GlobalForesterApiV1ControllersProjectsSharedResponseProject.  # noqa: E501
        :rtype: datetime
        """
        return self._created

    @created.setter
    def created(self, created):
        """Sets the created of this GlobalForesterApiV1ControllersProjectsSharedResponseProject.


        :param created: The created of this GlobalForesterApiV1ControllersProjectsSharedResponseProject.  # noqa: E501
        :type: datetime
        """

        self._created = created

    @property
    def updated(self):
        """Gets the updated of this GlobalForesterApiV1ControllersProjectsSharedResponseProject.  # noqa: E501


        :return: The updated of this GlobalForesterApiV1ControllersProjectsSharedResponseProject.  # noqa: E501
        :rtype: datetime
        """
        return self._updated

    @updated.setter
    def updated(self, updated):
        """Sets the updated of this GlobalForesterApiV1ControllersProjectsSharedResponseProject.


        :param updated: The updated of this GlobalForesterApiV1ControllersProjectsSharedResponseProject.  # noqa: E501
        :type: datetime
        """

        self._updated = updated

    @property
    def name(self):
        """Gets the name of this GlobalForesterApiV1ControllersProjectsSharedResponseProject.  # noqa: E501


        :return: The name of this GlobalForesterApiV1ControllersProjectsSharedResponseProject.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this GlobalForesterApiV1ControllersProjectsSharedResponseProject.


        :param name: The name of this GlobalForesterApiV1ControllersProjectsSharedResponseProject.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def links(self):
        """Gets the links of this GlobalForesterApiV1ControllersProjectsSharedResponseProject.  # noqa: E501


        :return: The links of this GlobalForesterApiV1ControllersProjectsSharedResponseProject.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this GlobalForesterApiV1ControllersProjectsSharedResponseProject.


        :param links: The links of this GlobalForesterApiV1ControllersProjectsSharedResponseProject.  # noqa: E501
        :type: dict(str, str)
        """

        self._links = links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GlobalForesterApiV1ControllersProjectsSharedResponseProject, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GlobalForesterApiV1ControllersProjectsSharedResponseProject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
