# coding: utf-8

"""
    Global Forester API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.global_forester_api_v1_controllers_managed_areas_shared_response_managed_area import GlobalForesterApiV1ControllersManagedAreasSharedResponseManagedArea  # noqa: E501
from swagger_client.rest import ApiException


class TestGlobalForesterApiV1ControllersManagedAreasSharedResponseManagedArea(unittest.TestCase):
    """GlobalForesterApiV1ControllersManagedAreasSharedResponseManagedArea unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGlobalForesterApiV1ControllersManagedAreasSharedResponseManagedArea(self):
        """Test GlobalForesterApiV1ControllersManagedAreasSharedResponseManagedArea"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.global_forester_api_v1_controllers_managed_areas_shared_response_managed_area.GlobalForesterApiV1ControllersManagedAreasSharedResponseManagedArea()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
