# coding: utf-8

"""
    Global Forester API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.rapid_orthophoto_files_api import RapidOrthophotoFilesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRapidOrthophotoFilesApi(unittest.TestCase):
    """RapidOrthophotoFilesApi unit test stubs"""

    def setUp(self):
        self.api = RapidOrthophotoFilesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_rapid_orthophoto_files(self):
        """Test case for get_rapid_orthophoto_files

        """
        pass

    def test_get_rapid_orthophoto_geo_package(self):
        """Test case for get_rapid_orthophoto_geo_package

        """
        pass

    def test_get_rapid_orthophoto_originals(self):
        """Test case for get_rapid_orthophoto_originals

        """
        pass


if __name__ == '__main__':
    unittest.main()
