# coding: utf-8

"""
    Global Forester API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_of_global_forester_api_v1_controllers_rapid_orthophotos_shared_response_rapid_orthophoto_geometry import OneOfGlobalForesterApiV1ControllersRapidOrthophotosSharedResponseRapidOrthophotoGeometry  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfGlobalForesterApiV1ControllersRapidOrthophotosSharedResponseRapidOrthophotoGeometry(unittest.TestCase):
    """OneOfGlobalForesterApiV1ControllersRapidOrthophotosSharedResponseRapidOrthophotoGeometry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfGlobalForesterApiV1ControllersRapidOrthophotosSharedResponseRapidOrthophotoGeometry(self):
        """Test OneOfGlobalForesterApiV1ControllersRapidOrthophotosSharedResponseRapidOrthophotoGeometry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_global_forester_api_v1_controllers_rapid_orthophotos_shared_response_rapid_orthophoto_geometry.OneOfGlobalForesterApiV1ControllersRapidOrthophotosSharedResponseRapidOrthophotoGeometry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
