# coding: utf-8

"""
    Global Forester API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.projects_api import ProjectsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self):
        self.api = ProjectsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_project(self):
        """Test case for delete_project

        """
        pass

    def test_get_project(self):
        """Test case for get_project

        """
        pass

    def test_get_projects(self):
        """Test case for get_projects

        """
        pass

    def test_post_project(self):
        """Test case for post_project

        """
        pass

    def test_put_project(self):
        """Test case for put_project

        """
        pass


if __name__ == '__main__':
    unittest.main()
