# coding: utf-8

"""
    Global Forester API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.observations_api import ObservationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestObservationsApi(unittest.TestCase):
    """ObservationsApi unit test stubs"""

    def setUp(self):
        self.api = ObservationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_observation(self):
        """Test case for delete_observation

        """
        pass

    def test_get_observation(self):
        """Test case for get_observation

        """
        pass

    def test_get_observations(self):
        """Test case for get_observations

        """
        pass

    def test_post_observation(self):
        """Test case for post_observation

        """
        pass

    def test_put_observation(self):
        """Test case for put_observation

        """
        pass


if __name__ == '__main__':
    unittest.main()
