# coding: utf-8

"""
    Global Forester API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.geo_json_net_geometry_i_geometry_object import GeoJSONNetGeometryIGeometryObject  # noqa: E501
from swagger_client.rest import ApiException


class TestGeoJSONNetGeometryIGeometryObject(unittest.TestCase):
    """GeoJSONNetGeometryIGeometryObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeoJSONNetGeometryIGeometryObject(self):
        """Test GeoJSONNetGeometryIGeometryObject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.geo_json_net_geometry_i_geometry_object.GeoJSONNetGeometryIGeometryObject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
