# coding: utf-8

"""
    Global Forester API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.rapid_orthophotos_api import RapidOrthophotosApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRapidOrthophotosApi(unittest.TestCase):
    """RapidOrthophotosApi unit test stubs"""

    def setUp(self):
        self.api = RapidOrthophotosApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_rapid_orthophoto_by_id(self):
        """Test case for get_rapid_orthophoto_by_id

        """
        pass

    def test_get_rapid_orthophotos(self):
        """Test case for get_rapid_orthophotos

        """
        pass


if __name__ == '__main__':
    unittest.main()
