# coding: utf-8

"""
    Global Forester API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.tracklogs_api import TracklogsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTracklogsApi(unittest.TestCase):
    """TracklogsApi unit test stubs"""

    def setUp(self):
        self.api = TracklogsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_tracklog(self):
        """Test case for delete_tracklog

        """
        pass

    def test_get_tracklog(self):
        """Test case for get_tracklog

        """
        pass

    def test_get_tracklogs(self):
        """Test case for get_tracklogs

        """
        pass

    def test_post_tracklog(self):
        """Test case for post_tracklog

        """
        pass

    def test_put_tracklog(self):
        """Test case for put_tracklog

        """
        pass


if __name__ == '__main__':
    unittest.main()
