# coding: utf-8

"""
    Global Forester API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.global_forester_api_v1_controllers_projects_shared_response_project import GlobalForesterApiV1ControllersProjectsSharedResponseProject  # noqa: E501
from swagger_client.rest import ApiException


class TestGlobalForesterApiV1ControllersProjectsSharedResponseProject(unittest.TestCase):
    """GlobalForesterApiV1ControllersProjectsSharedResponseProject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGlobalForesterApiV1ControllersProjectsSharedResponseProject(self):
        """Test GlobalForesterApiV1ControllersProjectsSharedResponseProject"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.global_forester_api_v1_controllers_projects_shared_response_project.GlobalForesterApiV1ControllersProjectsSharedResponseProject()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
