# coding: utf-8

"""
    Global Forester API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.managed_areas_api import ManagedAreasApi  # noqa: E501
from swagger_client.rest import ApiException


class TestManagedAreasApi(unittest.TestCase):
    """ManagedAreasApi unit test stubs"""

    def setUp(self):
        self.api = ManagedAreasApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_managed_area(self):
        """Test case for delete_managed_area

        """
        pass

    def test_get_managed_area(self):
        """Test case for get_managed_area

        """
        pass

    def test_get_managed_areas(self):
        """Test case for get_managed_areas

        """
        pass

    def test_post_managed_area(self):
        """Test case for post_managed_area

        """
        pass

    def test_put_managed_area(self):
        """Test case for put_managed_area

        """
        pass


if __name__ == '__main__':
    unittest.main()
