# coding: utf-8

"""
    Global Forester API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_of_global_forester_api_v1_controllers_observations_shared_response_observation_geometry import OneOfGlobalForesterApiV1ControllersObservationsSharedResponseObservationGeometry  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfGlobalForesterApiV1ControllersObservationsSharedResponseObservationGeometry(unittest.TestCase):
    """OneOfGlobalForesterApiV1ControllersObservationsSharedResponseObservationGeometry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfGlobalForesterApiV1ControllersObservationsSharedResponseObservationGeometry(self):
        """Test OneOfGlobalForesterApiV1ControllersObservationsSharedResponseObservationGeometry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_global_forester_api_v1_controllers_observations_shared_response_observation_geometry.OneOfGlobalForesterApiV1ControllersObservationsSharedResponseObservationGeometry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
