# coding: utf-8

"""
    Global Forester API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.teams_api import TeamsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTeamsApi(unittest.TestCase):
    """TeamsApi unit test stubs"""

    def setUp(self):
        self.api = TeamsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_team(self):
        """Test case for delete_team

        """
        pass

    def test_get_team(self):
        """Test case for get_team

        """
        pass

    def test_get_teams(self):
        """Test case for get_teams

        """
        pass

    def test_post_team(self):
        """Test case for post_team

        """
        pass

    def test_put_team(self):
        """Test case for put_team

        """
        pass


if __name__ == '__main__':
    unittest.main()
