# coding: utf-8

"""
    Global Forester API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.global_forester_api_v1_controllers_teams_shared_response_team import GlobalForesterApiV1ControllersTeamsSharedResponseTeam  # noqa: E501
from swagger_client.rest import ApiException


class TestGlobalForesterApiV1ControllersTeamsSharedResponseTeam(unittest.TestCase):
    """GlobalForesterApiV1ControllersTeamsSharedResponseTeam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGlobalForesterApiV1ControllersTeamsSharedResponseTeam(self):
        """Test GlobalForesterApiV1ControllersTeamsSharedResponseTeam"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.global_forester_api_v1_controllers_teams_shared_response_team.GlobalForesterApiV1ControllersTeamsSharedResponseTeam()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
