# coding: utf-8

"""
    Global Forester API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.observation_files_api import ObservationFilesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestObservationFilesApi(unittest.TestCase):
    """ObservationFilesApi unit test stubs"""

    def setUp(self):
        self.api = ObservationFilesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_image(self):
        """Test case for get_image

        """
        pass

    def test_get_observation_files(self):
        """Test case for get_observation_files

        """
        pass


if __name__ == '__main__':
    unittest.main()
